# Generated by Django 6.1.1 on 2026-09-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=128, unique=True)),
                ('source_url', models.URLField(max_length=512)),
                ('license_terms', models.TextField(blank=True, default='')),
                ('attribution_text', models.CharField(max_length=255)),
                ('refresh_policy', models.CharField(default='daily_batch', max_length=128)),
            ],
            options={
                'db_table': 'data_sources',
            },
        ),
        migrations.CreateModel(
            name='MarketObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(db_index=True, max_length=64)),
                ('value_decimal', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit', models.CharField(default='INR', max_length=32)),
                ('period', models.CharField(db_index=True, max_length=32)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('freshness', models.CharField(choices=[('current', 'Current'), ('delayed', 'Delayed'), ('stale', 'Stale'), ('historical', 'Historical')], default='historical', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='companies.company')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='companies.security')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_data.datasource')),
            ],
            options={
                'db_table': 'market_observations',
                'indexes': [models.Index(fields=['company', 'metric', 'period'], name='market_obse_company_90f1df_idx'), models.Index(fields=['security', 'observed_at'], name='market_obse_securit_774346_idx')],
            },
        ),
    ]
