# Generated by Django 6.1.1 on 2026-09-30 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, default='default_user', max_length=128)),
                ('title', models.CharField(default='New Research Session', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, default='default_user', max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('symbols', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'watchlists',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('schema_version', models.CharField(default='v1.2-grounded', max_length=32)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('safety_label', models.CharField(blank=True, default='factual_research', max_length=32)),
                ('citations_json', models.JSONField(blank=True, default=list)),
                ('numeric_claims_json', models.JSONField(blank=True, default=list)),
                ('limitations_json', models.JSONField(blank=True, default=list)),
                ('tool_trace_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_sessions.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
