# Generated by Django 6.1.1 on 2026-09-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32, unique=True)),
                ('template_hash', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('active_flag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prompt_versions',
            },
        ),
        migrations.CreateModel(
            name='ToolRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=128)),
                ('tool_name', models.CharField(db_index=True, max_length=64)),
                ('input_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(default='success', max_length=32)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('source_id', models.CharField(blank=True, default='', max_length=128)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tool_runs',
                'ordering': ['created_at'],
            },
        ),
    ]
