# Generated by Django 6.1.1 on 2026-09-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(db_index=True, max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('sector', models.CharField(db_index=True, max_length=128)),
                ('industry', models.CharField(blank=True, default='', max_length=128)),
                ('identifiers_json', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(db_index=True, max_length=16)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('isin', models.CharField(db_index=True, max_length=32)),
                ('instrument_type', models.CharField(default='EQ', max_length=32)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'securities',
                'db_table': 'securities',
                'unique_together': {('exchange', 'symbol')},
            },
        ),
    ]
