# Generated by Django 6.1.1 on 2026-09-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(db_index=True, max_length=16)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('headline', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('source_url', models.URLField(max_length=512)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='companies.company')),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['company', 'category'], name='announcemen_company_ebcc0a_idx'), models.Index(fields=['published_at'], name='announcemen_publish_6b0e06_idx')],
            },
        ),
    ]
