# Generated by Django 6.1.1 on 2026-09-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('annual_report', 'Annual Report'), ('earnings_call', 'Earnings Call Transcript'), ('presentation', 'Investor Presentation'), ('financial_results', 'Financial Results / Filing')], db_index=True, max_length=64)),
                ('fiscal_period', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=512)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_data.datasource')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(db_index=True)),
                ('page_no', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('vector_key', models.CharField(blank=True, default='', max_length=64)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'db_table': 'document_chunks',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'fiscal_period', 'document_type'], name='documents_company_b957fd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'page_no'], name='document_ch_documen_1a23ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
