# Generated by Django 5.2.17 on 2026-10-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_fund_and_macro_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=32)),
                ('headline', models.CharField(max_length=512)),
                ('category', models.CharField(choices=[('results', 'Results'), ('board_changes', 'Board Changes'), ('pledges', 'Pledges'), ('fundraises', 'Fundraises'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(max_length=32)),
                ('source_url', models.URLField(max_length=512)),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('approval_status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(default='My watchlist', max_length=100)),
                ('tickers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
