# Generated by Django 5.2.17 on 2026-10-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_announcement_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='correlation_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
